GET http://localhost:3000/pets

###

GET http://localhost:3000/pets/764ed855-bb09-4d81-a1b6-fe840c0224af


###

POST http://localhost:3000/pets
Content-Type: application/json

{
    "name": "Toto",
    "type": "cat"
}

###

PUT http://localhost:3000/pets/764ed855-bb09-4d81-a1b6-fe840c0224af
Content-Type: application/json

{
    "name": "Garfield",
    "type": "cat",
    "breed": "Persian",
    "gender": "Male"
}

###

DELETE http://localhost:3000/pets/764ed855-bb09-4d81-a1b6-fe840c0224af
Content-Type: application/json