GET http://localhost:3000/pets

###
GET http://localhost:3000/pets/12e3e004-6ca5-4312-ba39-b7e90bf7450b


###
POST http://localhost:3000/pets
Content-Type: application/json

{
    "name": "Garfield",
    "type": "cat",
    "customer_id": "adcc175d-cf77-4383-8ab8-46706edfc989"
}

###
PUT http://localhost:3000/pets/12e3e004-6ca5-4312-ba39-b7e90bf7450b
Content-Type: application/json

{
    "name": "Ravena",
    "type": "dog",
    "breed": "Boxer",
    "gender": "Female"
}


###
GET http://localhost:3000/users

###
GET http://localhost:3000/pets/12e3e004-6ca5-4312-ba39-b7e90bf7450b

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Paul Mcartney",
    "email": "paul5@mail.com",
    "password": "Pass123456"
}

###
DELETE http://localhost:3000/pets/779f1ed5-0047-42c2-86c1-21f795e7b05d
Content-Type: application/json

###
GET http://localhost:3000/customers

###
GET http://localhost:3000/customers/adcc175d-cf77-4383-8ab8-46706edfc989

###
POST http://localhost:3000/customers
Content-Type: application/json

{
    "name": "Paul Mcartney",
    "email": "paul5@mail.com"
}

###
DELETE http://localhost:3000/customers/779f1ed5-0047-42c2-86c1-21f795e7b05d
Content-Type: application/json